# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Our First Github Action 
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run : echo world
      - name: second hello world with multiline
        run: |
            echo hello
            echo world
            echo "sasa"
            python --version

