
name: matrix
on: [push]
jobs:
  first-job:
    runs-on: "ubuntu-latest"
    strategy: 
      matrix:
        numbers: [1,2,3,4]
      max-parallel: 3
    steps:
      - name: check-if-even
        run: echo ${{matrix.numbers}}
        if: ${{matrix.numbers > 2}} 
      - name: check-if-odd
        run: echo ${{matrix.numbers}}
        if: ${{matrix.numbers}}%2!=0