# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: our action Pipeline
on:
  pull_request:
    types:
      - "closed"
      - "opened"
jobs:
  first-jobs:
    if: ${{ github.event.action }} == "closed"
    runs-on: ubuntu-latest
    steps: 
      - name: test-step
        run: ls

  second-jobs:
    runs-on: ubuntu-latest
    steps: 
      - name: test-step
        run: ls
        